# Generated by Django 2.2.20 on 2021-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdest', models.CharField(max_length=30)),
                ('tdest', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=30)),
                ('retur', models.CharField(max_length=30)),
            ],
        ),
    ]
