# Generated by Django 2.2.20 on 2021-05-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contactuy',
        ),
    ]
