# Generated by Django 2.2.20 on 2021-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_remove_contactuy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuy',
            name='country',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
