# Generated by Django 2.2.20 on 2021-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_contactuy_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='classi',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
