# Generated by Django 2.2.20 on 2021-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0007_flight_classi'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='passe',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
