# Generated by Django 2.2.20 on 2021-05-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_auto_20210511_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactuy',
            new_name='Querie',
        ),
    ]
