# Generated by Django 2.2.20 on 2021-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='payID',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
