# Generated by Django 2.2.20 on 2021-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_pay_payid'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ticketID',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
