# Generated by Django 2.2.20 on 2021-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0014_flight_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fNO',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
