# Generated by Django 2.2.20 on 2021-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0015_flight_fno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('netname', models.CharField(max_length=20)),
                ('tID', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pay',
            name='uname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='uname',
            field=models.CharField(max_length=20),
        ),
    ]
