# Generated by Django 2.2.20 on 2021-05-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0017_auto_20210514_2252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Netpay',
        ),
    ]
