# Generated by Django 2.2.20 on 2021-05-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0020_remove_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
