# Generated by Django 2.2.20 on 2021-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0021_flight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
