# Generated by Django 2.2.20 on 2021-05-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0022_auto_20210515_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
    ]
