# Generated by Django 2.2.20 on 2021-05-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0025_pay_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('payID', models.CharField(max_length=15)),
                ('usr', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pay',
            name='price',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
