# Generated by Django 2.2.20 on 2021-05-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0026_auto_20210515_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='number',
        ),
    ]
