# Generated by Django 2.2.20 on 2021-05-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0027_auto_20210515_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='card',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='expdate',
        ),
    ]
