# Generated by Django 2.2.20 on 2021-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0028_auto_20210516_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='price',
        ),
        migrations.AddField(
            model_name='pay',
            name='amount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
