# Generated by Django 2.2.20 on 2021-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0029_auto_20210516_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='netpay',
            name='price',
        ),
        migrations.AddField(
            model_name='netpay',
            name='amount',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
