# Generated by Django 2.2.20 on 2021-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0030_auto_20210516_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('bID', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=30)),
                ('checkin', models.CharField(max_length=20)),
                ('checkout', models.CharField(max_length=20)),
                ('rooms', models.CharField(max_length=10)),
                ('adults', models.CharField(max_length=10)),
                ('children', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
