# Generated by Django 2.2.20 on 2021-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0031_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
