# Generated by Django 2.2.20 on 2021-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0032_hotel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromd', models.CharField(max_length=20)),
                ('tod', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=20)),
            ],
        ),
    ]
