# Generated by Django 2.2.20 on 2021-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0033_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='trname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
