# Generated by Django 2.2.20 on 2021-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0034_train_trname'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='trno',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
