# Generated by Django 3.2.3 on 2021-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0035_train_trno'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='passe',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
