# Generated by Django 3.2.3 on 2021-05-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0036_train_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='uname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
