# Generated by Django 3.2.3 on 2021-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0037_train_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('ticketID', models.CharField(max_length=20)),
                ('fromd', models.CharField(max_length=20)),
                ('tod', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('clas', models.CharField(max_length=20)),
                ('passe', models.CharField(max_length=5)),
                ('travel', models.CharField(max_length=30)),
            ],
        ),
    ]
